import Head from "next/head";
import Header from "../feature/Header/Header";
import HomeComponent from "../shared/components/HomeComponent";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Header />
      </header>

      <main>
        <HomeComponent />
      </main>

      <footer></footer>
    </div>
  );
}
