import Head from "next/head";
import MoviesComponent from "../../shared/components/HomeComponent/moviesComponent";
import Header from "../../feature/Header/Header";

export default function Home() {
  
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Header />
      </header>

      <main>
        <MoviesComponent />
      </main>

      <footer></footer>
    </div>
  );
}
