import Head from "next/head";

import SeriesContainer from "../../feature/series/seriesContainer";
import Header from "../../shared/Header/header";

export default function Series() {
  return (
    <div>
      <Head>
        <title>Series</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Header/>
      </header>
      <main>

        <SeriesContainer/>

      </main>

      <footer></footer>
    </div>
  );
}
